include $(TOPDIR)/rules.mk

LUCI_TITLE:=WDTT VPN Client
LUCI_DEPENDS:=+wdtt-client +luci-base +wireguard-tools +kmod-wireguard

PKG_LICENSE:=GPL-3.0-only

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
